# Generated by Django 4.1.3 on 2022-12-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_provider_service_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diler',
            name='date_last_auth',
        ),
        migrations.RemoveField(
            model_name='diler',
            name='date_register',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='date_last_auth',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='date_register',
        ),
    ]
