# Generated by Django 4.1.3 on 2023-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон производства'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='implements',
            field=models.ManyToManyField(blank=True, null=True, to='core.implement', verbose_name='Фурнитуры'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='core.region', verbose_name='Регионы'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_phone',
            field=models.CharField(default='', max_length=12, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='shapes',
            field=models.ManyToManyField(blank=True, null=True, to='core.shape', verbose_name='Профили'),
        ),
    ]
