# Generated by Django 4.1.3 on 2023-05-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_quantity_options_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Автор КП'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='comment',
            field=models.TextField(null=True, verbose_name='Кооментарий'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='date',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='file',
            field=models.FileField(upload_to='providers/quantity/files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='implement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.implement', verbose_name='Фурнитура'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='price',
            field=models.FloatField(verbose_name='Предложенная цена'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shape', verbose_name='Профиль'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('file', models.FileField(upload_to='manager/files')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
    ]
