# Generated by Django 4.1.3 on 2023-05-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quantity_author_alter_quantity_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий менеджера')),
                ('diler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='DilerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий менеджера')),
                ('diler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.diler')),
            ],
        ),
    ]
