# Generated by Django 4.1.3 on 2023-05-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicaldiler_historicalorder_historicalprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dilercomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='providercomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
