# Generated by Django 4.1.3 on 2023-05-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dilercomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dilercomment',
            name='diler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diler'),
        ),
        migrations.AlterField(
            model_name='providercomment',
            name='diler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider'),
        ),
    ]
