# Generated by Django 4.1.3 on 2023-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dilercomment_diler_alter_providercomment_diler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='implement',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalprice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprovider',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalquantity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalquantity',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalquantity',
            name='implement',
        ),
        migrations.RemoveField(
            model_name='historicalquantity',
            name='order',
        ),
        migrations.RemoveField(
            model_name='historicalquantity',
            name='shape',
        ),
        migrations.DeleteModel(
            name='HistoricalDiler',
        ),
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
        migrations.DeleteModel(
            name='HistoricalPrice',
        ),
        migrations.DeleteModel(
            name='HistoricalProvider',
        ),
        migrations.DeleteModel(
            name='HistoricalQuantity',
        ),
    ]
