# Generated by Django 4.1.3 on 2023-06-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_historicalorder_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
